language: node_js

cache:
  npm: false

before_install:
- curl -L https://unpkg.com/@pnpm/self-installer | node

install:
- pnpm install

script:
- pnpm run precommit

deploy:
- provider: npm
  edge: true
  # leave dist directory
  skip_cleanup: true
  api_key:
    secure: BhWaXxkMxSlPjdpkeQT2EvfjSKP22REoVoCXJw6ibn1sgoaGdyCD8N+gu56gW8QP5V2yuEv1EK6BuwB4GFL1X6qdAAx4m2jtGwzCqCuU4KlV5G/YaLJj5nlEzM3X6E6ANjm8L3pIBNKvE4IQyAlrbCc3aPfXElJR01itd4kswmW3Qij4ie7dNSjED9F1NqeFa+zKVwwbhpW2uddkgOcH0Ib+Jg3B8DYe/HgIyJv6UWr0YU9JboMJOk2mAfeFiD4ltvfxnSn2mb7p3lcHDqskMT58nUmzCW+QrsNPR2URMpfMnledlfaxom05QXKtelfAG4d/v588CIpSWuThIeEapCBtdG/UuHQxAOjiTtxboG1wsVgXItR/5t3PyTy7fMlW+jOFXSvhbMVWcOSx9tpkiMDArzeSml3gfYF23NGb/SAaDWsRlCabgfoBBR+qnjSYHDs20+0sVWDORY+59c4THTuclwWCho8qjQA96HCecuSTim2JyJtdK4yhYRmcsBSAbBXEO8wXtslEX674yQ8bkn77ksd+36kAd58eqFV+uVegVs0IdjMAfP7Jr3C3e7vz/QWMr5KYwgLesmv5u8nGaCL5KrU/B4d7gibdq3gxYv/8horEm64SPX9xF8xxngzvuBzvIV8QEiHgNy4gzjt7mHagJEawDaGfe7L+pdK9BHQ=
  email:
    secure: e1/sKtxgrDWVXj5UjjN30jA46XEa50tSNoHdQmGj0EHn3cGJYGPQI8DJiTw7Xspbphq3IWrmmtj6u6nzRqLnY8OJbkGBI9jUpO01kS5lP+X01LKmVb/FPC6I6W2xTCTJo0gSbD1oEECsm5ZvAM7iw+WSWcta78kXpnpb9pWHx0EarFwyl5bRGYXr3VnCuNSpaa836pNxIjepRk0RdpAOjrng+S8gUmKf9KiOJsndqYL3BDa5l9XqHfhiphwBGpDNtBQlhZWBFxA4nuq8KEpqQ3bSmfQ8OClvAmPaGdWFudlqYlI9H105XizzSxkL7d8NxxUEglBmh1kPxt3OJjYseBhP78AswloQ0mlwKiK7EUGG0BeIcRwpySqmMYCxP2nn8Rfw0C+WWtxEnIQgRXKFOcgxpsN8OxauE2Ru/B4rit9P1mcMX1/f6rmcgwPcZdfU1wdwH1O8zjXd13WXaHFuaX05uXy545Y06DV8WV2rK0wsQrFvOchBL/yrM2g8nfwoqaezcPVYxPwkITkFaLyZzjx13wz0LIlmsUutSefd/bbyPVQqSA9mfOZo8T/xZ/Cvb0qu7IDs89e/4Y542RekGmU/Jl+/jj6Uq3A/bJ8nsBsLAO3bD6tPzExeuVYnhmffhshzGSsCCdMpyocH36rWx0XAROmXCJh7GC76rU+/wY4=
  on:
    repo: Bessonov/set-project-references
    tags: true
    condition: "$TRAVIS_PULL_REQUEST = false"
